### ISSUE TITLE
Host it

### ISSUE THREAD

**Issue by NotSoMik** [lplaat/1Fichier-Download-Tool#1]
Can you host it for at least 1 day so I cant test it since I dont know python, I just wanted to check if the can download this link https://1fichier.com/?wogbxcvzs3dvm3wiqbtu

**Comment by lplaat** [comment]
Hi, this code is no longer maintain. But to run it is very simple. Just install the latest version of python and edit the text "download-url" to youre 1fichier link. And install the required libraries with these commands.
`pip install fake-useragent`
`pip install stem`
`pip install requests`
`pip install beautifulsoup4`
After that just run the command "python main.py" and it start downloading the url.
